### ISSUE TITLE
[TYPO] Operating Systems - Thread Design Considerations

### ISSUE THREAD

**Issue by xinyutan** [m4ttsch/omscs-notes-notes#11]
**What needs to be fixed?**
https://www.omscs-notes.com/operating-systems/thread-design-considerations/#kernel-vs-user-level-threads
Paragraph 3 last sentence:  "Different processes may ~user~ use entirely different user level thread libraries."

**Comment by m4ttsch** [comment]
Fixed [here](https://github.com/m4ttsch/omscs-notes-notes/commit/4b4610beb869e1d2098f5a39cc5d8e617fe41863)! Thank you for finding this. It means a lot to me!
