### ISSUE TITLE
[TYPO] incorrect exponential cdf

### ISSUE THREAD

**Issue by matt-raporte** [m4ttsch/omscs-notes-notes#18]
The CDF for Exp(λ) is incorrect [here](https://www.omscs-notes.com/simulation/random-variate-generation/#exponential-example). Should be 1-e^(-λx)

**Comment by m4ttsch** [comment]
Whoa! Big mistake. Thanks for pointing this out!

**Comment by m4ttsch** [comment]
Fixed [here](https://github.com/m4ttsch/omscs-notes-notes/commit/080f7b355751cdee16a2606ad32386c4179f6760)
