### ISSUE TITLE
[TYPO] Information Security - Law, Ethics, and Privacy

### ISSUE THREAD

**Issue by BenTrainor** [m4ttsch/omscs-notes-notes#20]
**What needs to be fixed?**
Please be specific as possible and add a link to the relevant file/lines.

Additionally, lawmaking is a slow process, and the stakes are high for **focussed** attackers.

**Comment by m4ttsch** [comment]
https://github.com/m4ttsch/omscs-notes-notes/commit/b3948e3333666d80e28e0f2d5a6c127696394a12
