### ISSUE TITLE
[TYPO] Information Security - Cyber Security

### ISSUE THREAD

**Issue by BenTrainor** [m4ttsch/omscs-notes-notes#22]
**What needs to be fixed?**
Please be specific as possible and add a link to the relevant file/lines.

"we can define risk leverage **L = (post - pre) / cost**"

**Risk leverage should be (pre - post) / cost**. If pre is $5, post $4, and cost $0.50, then we have a risk leverage of 2, and the security fix should be implemented. In the above definition, the risk leverage would be -2, and would not be implemented despite the fix costing less than the amount of money saved by it.

**Comment by m4ttsch** [comment]
https://github.com/m4ttsch/omscs-notes-notes/commit/b3948e3333666d80e28e0f2d5a6c127696394a12
