### ISSUE TITLE
[TYPO] Information Security - Cyber Security

### ISSUE THREAD

**Issue by kbyrne661** [m4ttsch/omscs-notes-notes#23]
**What needs to be fixed?**
Please be specific as possible and add a link to the relevant file/lines.

https://www.omscs-notes.com/information-security/cyber-security/

The formula for risk leverage is shown as (post - pre)/cost, but it should be (pre - post)/cost. The former would generate a negative number since the risk exposure should always be lower after introducing a new control. The udacity lectures teach it as (pre - post)/cost.

**Comment by m4ttsch** [comment]
https://github.com/m4ttsch/omscs-notes-notes/commit/b3948e3333666d80e28e0f2d5a6c127696394a12
