### ISSUE TITLE
[TYPO] Simulation - Input Analysis

### ISSUE THREAD

**Issue by carrotbxh** [m4ttsch/omscs-notes-notes#26]
**What needs to be fixed?**
Please be specific as possible and add a link to the relevant file/lines.
![image](https://user-images.githubusercontent.com/54381510/101268700-57745180-3734-11eb-9087-5184a086ff16.png)

and the formulas after that are missing the n as well.

**Comment by m4ttsch** [comment]
https://github.com/m4ttsch/omscs-notes-notes/commit/b3948e3333666d80e28e0f2d5a6c127696394a12
