### ISSUE TITLE
[TYPO] Missing question in Midterm 1 Study Guide

### ISSUE THREAD

**Issue by calenrobinette** [m4ttsch/omscs-notes-notes#42]
In midterm-1-study-guide.md at line 680 there is a missing question. Only the answers are present.

**Comment by IcanBENCHurCAT** [comment]
seems like it is missing something like "what data is held within each element in a capability list?"

**Comment by m4ttsch** [comment]
Can either of you add a PR please?

**Comment by m4ttsch** [comment]
https://github.com/m4ttsch/omscs-notes-notes/pull/43
