### ISSUE TITLE
[TYPO] Information Security - Midterm 2 Study Guide

### ISSUE THREAD

**Issue by nasirhafeez** [m4ttsch/omscs-notes-notes#48]
[Midterm 2](https://www.omscs-notes.com/information-security/midterm-2-study-guide/#chapter-8-intrusion-detection)

The following typo exists on this page:

The base-rate fallacy of IDS states that if the numbers of intrusions are low compared to the number of legitimate `users` of a system then the false alarm rate will be high unless the test is extremely discriminating

It should be `uses` here instead of `users`.

**Comment by nasirhafeez** [comment]
<img width="548" alt="Screenshot 2021-05-01 111722" src="https://user-images.githubusercontent.com/38311694/116773419-c305e500-aa6e-11eb-8fd8-84f97a7445b1.png">

Relevant screenshot from the book.

**Comment by m4ttsch** [comment]
Are you comfortable submitting a PR to fix this?

**Comment by nasirhafeez** [comment]
Done. Please check:

https://github.com/m4ttsch/omscs-notes-notes/pull/50

**Comment by m4ttsch** [comment]
Merged! Thank you
