### ISSUE TITLE
[TYPO] Machine Learning Trading - Reading and Plotting Stock Data

### ISSUE THREAD

**Issue by rahulbajaj369** [m4ttsch/omscs-notes-notes#54]
**What needs to be fixed?**
Please be specific as possible and add a link to the relevant file/lines.

Compute Mean Volume Quiz Solution - 
Answer you have: "df['Values'].mean()"
Answer should be: "df['Volume'].mean()"

**Comment by m4ttsch** [comment]
Can you submit a PR?
