### ISSUE TITLE
[TYPO] Operating Systems - Virtualization

### ISSUE THREAD

**Issue by andrewleonard1693** [m4ttsch/omscs-notes-notes#56]
**What needs to be fixed?**
Please be specific as possible and add a link to the relevant file/lines.

Relevant section: https://www.omscs-notes.com/operating-systems/virtualization/#virtualization-models-bare-metal

Second paragraph: "In order words" should be "In other words"

**Comment by m4ttsch** [comment]
Can you submit a PR please?

**Comment by m4ttsch** [comment]
Fixed.
