### ISSUE TITLE
[TYPO] Information Security - How does the Os Implement ACL

### ISSUE THREAD

**Issue by manasmulay** [m4ttsch/omscs-notes-notes#62]
**What needs to be fixed?**
Please be specific as possible and add a link to the relevant file/lines.

Wrt file-descriptor table
https://www.omscs-notes.com/information-security/access-control/#how-does-the-os-implement-acl

`This table holds pointers to the inode table and contains all of the files currently being accessed by the given file.`

`being accessed by the given file.` should be `being accessed by the given process.`

**Comment by m4ttsch** [comment]
Can you submit a PR please?
