### ISSUE TITLE
[TYPO] Information Security - Security Protocols

### ISSUE THREAD

**Issue by ruchasathe** [m4ttsch/omscs-notes-notes#64]
**What needs to be fixed?**
Please be specific as possible and add a link to the relevant file/lines.

"Bob response with a random value r1, referred to as a challenge."
response -> responds. Security Protocols (Mutual Authentication: Shared Secret)

**Comment by m4ttsch** [comment]
Can you submit a PR please?

**Comment by m4ttsch** [comment]
Fixed.
