### ISSUE TITLE
[TYPO] Operating Systems - Scheduling

### ISSUE THREAD

**Issue by robson31** [m4ttsch/omscs-notes-notes#66]
**What needs to be fixed?**
Please be specific as possible and add a link to the relevant file/lines.

For metrics, our throughput stays the same, and our average wait and average completion time are on par with SJF, but without needing **the a priori knowledge** of execution times, which was said was unfeasible in a real system.

**Comment by m4ttsch** [comment]
Can you submit a PR please?
