### ISSUE TITLE
[TYPO] Operating Systems - Midterm Exam Review Questions

### ISSUE THREAD

**Issue by alepetri** [m4ttsch/omscs-notes-notes#72]
**What needs to be fixed?**
In the section "What is a system call?" the line "Examples of system calls include open, send, malloc." exists.
In the errata for those video slides, it states that she meant to use `mmap` (linux memory acquistion) instead of `malloc` (c memory acquistion).

**Comment by m4ttsch** [comment]
https://github.com/m4ttsch/omscs-notes-notes/commit/ed13d40b00ccbcb76058aebb10629b6b238f16d4
