### ISSUE TITLE
[TYPO] ML4T - How Hedge Funds Use the CAPM

### ISSUE THREAD

**Issue by tdisheng** [m4ttsch/omscs-notes-notes#73]
**What needs to be fixed?**
In the section Two Stock Scenario Quiz Solution, the line "Let's consider stock B now, which has a β of 2.0 and an α of -0.01. A β of 2.0 tells us that for every percentage point the market moves, stock A moves two percent. An α of -0.01 tells us that stock A will move 1% below its movement with the market." is probably meant to refer to stock B when talking about stock A.

**Comment by m4ttsch** [comment]
https://github.com/m4ttsch/omscs-notes-notes/commit/ed13d40b00ccbcb76058aebb10629b6b238f16d4
