### ISSUE TITLE
[TYPO] Secure Computer Systems - Mandatory Access Control

### ISSUE THREAD

**Issue by natsmith9** [m4ttsch/omscs-notes-notes#77]
**What needs to be fixed?**
Please be specific as possible and add a link to the relevant file/lines.
Under the Mandatory Access Control, Label Comparisons heading, there's an intersection operator instead of the "and" operator in the formal definition of determining which label is dominant--the lecture shows the use of and rather than an intersection of the level and compartment:

L1 > L2 (L1 dominates L2) if (L1.level \geq≥ L2.level) \cap∩ (L1.compartment \supset⊃ L2.compartment)
L1 < L2 (L1 is dominated by L2) if (L1.level \leq≤ L2.level) \cap∩ (L1.compartment \subset⊂ L2.compartment)
L1 = L2 if (L1.level = L2.level) \cap∩ (L1.compartment = L2.compartment)

**Comment by m4ttsch** [comment]
Can you submit a PR please?
