### ISSUE TITLE
[TYPO] Operating Systems - Distributed File Systems

### ISSUE THREAD

**Issue by ajisamudra** [m4ttsch/omscs-notes-notes#82]
Hi, I found a typo here
https://www.omscs-notes.com/operating-systems/distributed-file-systems/#sprint-dfs-from-analysis-to-design

~~Sprint~~ Sprite DFS from Analysis to Design

Anw, thanks for the great notes!

**Comment by m4ttsch** [comment]
Can you submit a PR please?

**Comment by m4ttsch** [comment]
Fixed this.
